// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEc-Cjh_JgeWHa7Sbp6Aw5UtLvQBSVH10',
    appId: '1:1009656958915:web:c65d249f0921835518b776',
    messagingSenderId: '1009656958915',
    projectId: 'fir-practice-54f70',
    authDomain: 'fir-practice-54f70.firebaseapp.com',
    storageBucket: 'fir-practice-54f70.firebasestorage.app',
    measurementId: 'G-M12TXSSRVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbEUN3wOQZe-YRQC4u9Hfkc3UI_ZWt1t8',
    appId: '1:1009656958915:android:3d5d389be6c86d3e18b776',
    messagingSenderId: '1009656958915',
    projectId: 'fir-practice-54f70',
    storageBucket: 'fir-practice-54f70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINN_Jc8e7KbOTgmtIbD8MBrjH3RqQm-w',
    appId: '1:1009656958915:ios:9e02ded73d9463c518b776',
    messagingSenderId: '1009656958915',
    projectId: 'fir-practice-54f70',
    storageBucket: 'fir-practice-54f70.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );
}
